server:
  port: 81
#  context-path: /web
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: weixin
    
logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG

wechat:
  mp:
    appId: wx2776dace00c5c8f3
    secret: 209be53caee56255622ee2a36e655628
    token: blueKite
    aesKey:    
